name: CI

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release      
  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
     
      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2            
        - name: Build Docker Image
          run:  docker build -t ${{secrets.DOCKER_HUB_USER}}/${{ secrets.IMAGE_NAME }}:${{ github.sha }} . 
        - name: Login to the account
          run:  echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u ${{secrets.DOCKER_HUB_USER}} --password-stdin
        - name: Push Docker Image
          run: docker push ${{secrets.DOCKER_HUB_USER}}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}
  deployment:
    runs-on: ubuntu-latest
    needs: docker
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2 
        - name: Clone the repository
          run: git clone https://x-access-token:${{ secrets.PAT }}@github.com/MariiaParakhina/readsphere_kubernetes.git
        - name: Update image tag in deployment file
          run: |
            cd readsphere_kubernetes
            sed -i 's|${{secrets.DOCKER_HUB_USER}}/${{ secrets.IMAGE_NAME }}:.*|${{secrets.DOCKER_HUB_USER}}/${{ secrets.IMAGE_NAME }}:${{ github.sha }}|g' ${{ secrets.PATH_DEPLOYMENT }}
        - name: Commit and push changes
          run: |
            cd readsphere_kubernetes
            git config --global user.email "${{ secrets.EMAIL }}"
            git config --global user.name "MariiaParakhina"
            git add .
            git commit -m "Update image tag"
            git push


