name: CI

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'

      - name: Install ReportGenerator
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Application
        run: dotnet build --configuration Release      
  test:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build and Test with Code Coverage
        run: |
          dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura        
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: MariiaParakhina/readsphere_api_gateway
      - name: Run Qodana Scan
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: set up gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      # - name: set up google SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with: 
      #     project_id: readsphere
      #     service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      #     export_default_credentials: true
      - name: build and push
        env:
          GOOGLE_PROJECT: readsphere
        run: |         
          docker build -t us-central1-docker.pkg.dev/readsphere/api-gateway/api-gateway  .
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev            
          docker push us-central1-docker.pkg.dev/readsphere/api-gateway/api-gateway
     
  deploy:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: set up gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Deploy to Cloud Run
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
          gcloud run deploy readsphere-api-gateway --image us-central1-docker.pkg.dev/readsphere/api-gateway/api-gateway
        
      # - name: Trigger Workflow
      #   run: |
      #       curl -X POST \
      #         -H "Accept: application/vnd.github.v3+json" \
      #         -H "Authorization: Bearer ${{ secrets.G_ACCESS_TOKEN }}" \
      #         -H "Content-Type: application/json" \
      #         -H "X-GitHub-Api-Version: 2022-11-28" \
      #         -d '{"ref": "main"}' \
      #         https://api.github.com/repos/MariiaParakhina/readsphere/actions/workflows/90898442/dispatches
 
